### ISSUE TITLE
Upgrade from Kloxo

### ISSUE THREAD

**Issue by DaltonSponholz** [mustafaramadhan/kloxo#10]
Is it possible to upgrade my server from kloxo to kloxo-mr?

**Comment by mustafaramadhan** [comment]
Read https://github.com/mustafaramadhan/kloxo/blob/dev/how-to-install.txt

Better register as a member to http://forum.mratwork.com

**Comment by DaltonSponholz** [comment]
After follow this tutorial, I get an Internal Server Error: http://news.adsantos.com.br:7778

All my services are down. What can I do? I read and did the warning before /script/upcp

**Comment by DaltonSponholz** [comment]
Starting kloxo-hiawatha: Error binding 0.0.0.0:7778

##                                                            [FAILED]

Parando o php-fpm:                                         [FAILED]

## Iniciando php-fpm:                                         [  OK  ]

**Comment by mustafaramadhan** [comment]
Please register to forum.mratwork.com for support.

This is my last response.
