### ISSUE TITLE
PHP FPM settings for client always resets

### ISSUE THREAD

**Issue by aalasolutions-zz** [mustafaramadhan/kloxo#14]
Hi, 

I am using _Kloxo-MR 7.0.0.b-2015103001_ for a client. I have to allow 2gb file upload and 5 hours max upload time due to him uploading from a mobile network. 

I have set the changes in admin panel for advance php, and I also have updated the following files

```
/etc/php-fpm.d/clientabc.config <-- This is my client's settings
/etc/php-fpm.d/default.config
/etc/php-fpm.d/admin.config
```

Now when ever I do, restart-all services, or do fix-all it always resets the values back to default, 

a) I can see that in the Advance PHP Settings on webpanel, settings are proper 2gb
b) default and admin config files -- one  value _request time out_
c) clientabc.config file rolled back fully, means all the upload size, max time out etc are refreshed.

This is causing lots of trouble at the moment.

**Comment by mustafaramadhan** [comment]
1. Update your Kloxo-MR 7.0
2. php setting for client via 'admin > clients > (select 1 client) > php configure > advanced php configure'. Access to 'admin  > php configure > advanced php configure' is for admin
3. Better post your issue in forum.mratwork.com
