### ISSUE TITLE
can't install kloxo mr

### ISSUE THREAD

**Issue by han220805** [mustafaramadhan/kloxo#15]
Can You help me sir? When I type "yum update mratwork-\* -y" there is an error on 
http://yum.mariadb.org/10.0/centos7-x86/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623
and error on this

failure: repodata/repomd.xml from mratwork-release-version-arch: [Errno 256] No more mirrors to try.
https://github.com/mustafaramadhan/kloxo/raw/rpms/release/centos7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
....
I have one server running kloxo-mr 7 running smoothly, I prefer to move on a new server, but I got this error, please help me ASAP

**Comment by mustafaramadhan** [comment]
Still not work in CentOS 7. Better use CentOS 6.

**Comment by han220805** [comment]
Ok.. I'll try.. Thanks a lot
