### ISSUE TITLE
UPGRADE THE PHP VERSION

### ISSUE THREAD

**Issue by hawkao** [mustafaramadhan/kloxo#16]
Which year is it now why you are still using PHP 5.2/5.3/5.4?
Time for 5.6 and 7.0!
Please UPGRADE the DEFAULT PHP VERSION to PHP 5.6.18 , thanks!

**Comment by mustafaramadhan** [comment]
No problem to change to php version under Kloxo-MR. Just use 'php branch' (for Kloxo-MR 6.5/7.0) and 'php used' (after install 'multiple php' (from 5.2 to 7.0).

**Comment by techvn** [comment]
How can i upgrade php to 5.6x or higher in Kloxo server?

**Comment by mustafaramadhan** [comment]
Any problems if you register and then post your question in forum mratwork.com.

**Comment by sachindadhaniya** [comment]
after change in PHP Branch no change in php version.

**Comment by mustafaramadhan** [comment]
Please ask to https;//forum.mratwork.com for all Kloxo-MR issues
