### ISSUE TITLE
After the cleanup is finished does not automatically restart the required environment.

### ISSUE THREAD

**Issue by Aloento** [mustafaramadhan/kloxo#19]
### After the cleanup is finished does not automatically restart the required environment.
- Fix php services
  sh: php: command not found
  sh: php: command not found
  sh: php: command not found
  sh: php: command not found
  sh: php: command not found
  sh: php: command not found
  sh: php: command not found
- Fix mail-all services
- Fix ftp-all services
- Fix skeleton services
  sh: php: command not found
  Fixing Hiawatha service
  **\* Executing Update (cleanup) - END ***

**\* Restart services - BEGIN ***
- For help, type '/script/restart-all [--help|-h]'
  **\* Restart services - END ***

**\* Process Time: 00:00:02:07.127171 (dd:hh:mm:ss:xxxxxx) ***
## Here are some suggestions:

I suggest delete the specified php version features.
Logo on the left is recommended that the user of the Logo of Kloxo-MR.
It proposed the deletion of Ajax.
1 IP uses a plurality of SSL.
Change FTP port and MySQL port directly Kloxo in.
Program automatic restart function.
Let SSH management becomes possible Kloxo-MR and use HTML5.
Let Kloxo-MR becomes more compact.
......
## Here is what I do:

Making Chinese translation.
Promotion Kloxo-MR in China and solve their problems.
Promotion Kloxo-MR.
.......

**Comment by mustafaramadhan** [comment]
Thanks for your promote Kloxo-MR in China.

For your issue, better involve to forum.mratwork.com.

**Comment by Aloento** [comment]
Forum for phone compatibility is not good, so I did not get a long time successfully registered.

**Comment by Aloento** [comment]
# Urgent issues:@mustafaramadhan

## FTP can not be used after the upgrade.

## The new installation Kloxo-MR, FTP can not be used.

FTP return 530 error, I try to repair failed.

Suggest a key migration server function.

**Comment by mustafaramadhan** [comment]
Sorry, only forum.mratwork.com as Kloxo-MR support. Not here.

Yes, possible ftp failed if update from (very) old version because change pure-ftpd service from xinetd to pure-ftpd init. Go to 'ftp configure' to fix this issue.
