### ISSUE TITLE
Can not login.

### ISSUE THREAD

**Issue by Aloento** [mustafaramadhan/kloxo#22]
I am now a very serious mistake landed.
Regardless I can not log in to any password kloxo-mr.
I was a new installation, Kloxo-MR 7.0.0.b-2016072301
Alert: Login Unsuccessful

**Comment by mustafaramadhan** [comment]
Posting your issue in https://forum.mratwork.com.

Kloxo-MR is open-source project. So, only forum as free support.

**Comment by Aloento** [comment]
https://forum.mratwork.com/kloxo-mr-technical-helps/can-not-login/
