### ISSUE TITLE
Does it support ubuntu 16.04 LTS?

### ISSUE THREAD

**Issue by LoganDark** [mustafaramadhan/kloxo#23]
I was not able to find this information anywhere so just asking.

**Comment by mustafaramadhan** [comment]
Sadly, no plan to porting to other than CentOS (and their variants).

Instead porting to others, more consentration for more and better features (like multiple php in php-fpm mode, multiple webserver and so on).

**Comment by LoganDark** [comment]
Oh, ok, I'll just use webmin then.
