### ISSUE TITLE
Centalt repository seems to be damaged, mirrorlist not found

### ISSUE THREAD

**Issue by slrslr** [mustafaramadhan/kloxo#24]
Hi,

when trying to install KloxoMR 7 according to the manual, im invited to do command: yum update mratwork-\* -y

But it returns:

Error: Cannot retrieve metalink for repository: mratwork-epel. Please verify its path and try again

I tried to replace https by http in this line:
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-$releasever&arch=$basearch

And it seems to went thru, but next error is:

```
http://centos.alt.ru/repository/centos/6/i386/repodata/repomd.xml: [Errno 14] Peer cert cannot be verified or peer cert invalid
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: mratwork-centalt. Please verify its path and try again
```

I think alt.ru seems to be damaged. When i uncomment mirrorlist= in the "[mratwork-centalt]" section, then error is:

```
Could not retrieve mirrorlist http://rpms.mratwork.com/repo/mirrors/centalt-centos-6-i386-mirrors.txt error was
14: PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
```

Here is some alternative, but not sure if it contains all necessary data? https://webpatron.net/en/blog/sysadmin-notes/item/53-mirror-centalt-repository-for-centos-5-x-6-x

Thank you

CentOS release 6.4 (Final)
Linux host.name.tld 2.6.32-042stab093.5 #1 SMP Wed Sep 10 17:39:49 MSK 2014 i686 i686 i386 GNU/Linux

**Comment by mustafaramadhan** [comment]
Centalt dead/down more than 1 year and then Kloxo-MR not used it after. So, remove all mratwork repo with 'yum remove mratwork\* -y' and then install again with 'rpm -ivh https://github.com/mustafaramadhan/kloxo/raw/rpms/release/neutral/noarch/mratwork-release-0.0.1-1.noarch.rpm; yum update mratwork\* -y'

**Comment by mustafaramadhan** [comment]
Follow https://github.com/mustafaramadhan/kloxo/blob/dev/how-to-install.txt
