### ISSUE TITLE
Multi Server

### ISSUE THREAD

**Issue by velusopensource** [mustafaramadhan/kloxo#29]
Hello, im looking to use this in a multi server support, it says in wiki pedia that you provide multi server support, what im looking to do is, have seperate email dns and web servers, also do you have an api system for it so i can create a web hosting billing system so then i can create clients with this system

**Comment by mustafaramadhan** [comment]
At current version (version 7.0), multiple web server only possible if select nginx-/lighttpd-/hiawatha-proxy where every domain can select nginx only or nginx-proxy (example for nginx-proxy).

I have a plan to make full multiple web server in version 7.1 (not release yet) where every domains can select nginx, lighttpd, hiawatha, nginx-proxy, lighttpd-proxy, hiawatha-proxy or apache.

For Kloxo-API, read https://forum.mratwork.com/kloxo-mr-development/kloxo-api-23797/

**Comment by velusopensource** [comment]
when will 7.1 be ready? and also when will the docs be done?

**Comment by mustafaramadhan** [comment]
Will be alpha step for 7.1 after 17 Aug 2017 Ready for multiple webserver in beta step.
