### ISSUE TITLE
Error: Cannot retreive repository metadata (repomd.xml) for repository: mratwork-varnish-3.0. Please verify its path and try again

### ISSUE THREAD

**Issue by j33pi** [mustafaramadhan/kloxo#33]
hello, 
im trying to install kloxomr on my VPS Centos6.5, i've followed  you steps but i got this error: 

https://repo.varnish-cache.org/redhat/varnish-3.0/el6/x86_64/repodata/repomd.xml: [Erno 14] PYCURL ERROR 22 - "The requested URL returned error: 410 repo"
Trying other mirror. 
Error: Cannot retreive repository metadata (repomd.xml) for repository: mratwork-varnish-3.0. Please verify its path and try again

when i go on" https://repo.varnish-cache.org/redhat/varnish-3.0/el6/x86_64/repodata/repomd.xml" they say "repo.varnish-cache.org is no more" so i dont know what to do now! please help me, im beginner in centos, and excuse my english but im french. thanks you

**Comment by mustafaramadhan** [comment]
Already update mratwork.repo to adjustment for latest varnish.
