### ISSUE TITLE
Installing KloxoMR repo.varnish-cache.org is no more.

### ISSUE THREAD

**Issue by bejaranoaqp** [mustafaramadhan/kloxo#38]
![screenshot_57](https://user-images.githubusercontent.com/21958647/33248816-208b9648-d2f5-11e7-939f-a01c1eeba44b.png)

http://repo.varnish-cache.org/redhat/varnish-3.0/el7/x86_64/repodata/repomd.xml

**Comment by murshed** [comment]
I have removed that repo link from my box. Everything is fine.
Hope, MR added the new link.

**Comment by mustafaramadhan** [comment]
Already fixed
