### ISSUE TITLE
Bind DNS problems

### ISSUE THREAD

**Issue by almas** [mustafaramadhan/kloxo#4]
Kloxo-MR 7 last version. Bind DNS can't start because of /etc/rndc.key content. I changed key name in this file rndckey to rndc-key then it works.

My system: OpenVZ VPS with CentOS 5.11

Also named.master.conf file is empty. Then Bind can't load zone. I ran /script/fixdns but it can't fix too.

'sh /script/fix-all; sh /script/restart-all' also can't fix.

There are zone files in nsd/conf/master folder. But bind doesn't load zone files. How can I fix this. It's critical.

**Comment by mustafaramadhan** [comment]
Bind, nsd and yadifu using the same domain zones in /opt/configs/nsd/conf/master.

To fix bind issue, try switch to other (let say nsd) and switch back to bind in 'switch programs'.

**Comment by almas** [comment]
I tried it already. But it can't helped. I switched nsd and back to bind. 
I checked files in /opt/configs/nsd/conf/master and there are files.
But Bind can't load zones. There was /opt/configs/bind/conf/defaults/named.master.conf is empty. Is this can cause?

**Comment by almas** [comment]
I found cause and solution.
My domains had field syncserver 2 or more in database. I changed it to localhost. Then it go on.
If syncserver multi then /script/fixdns failing.

It fixed:
UPDATE `dns` SET `syncserver`='localhost' WHERE syncserver='localhost,ns2.nameserver.com' 

I upgraded from Kloxo 6.1.19.
Official Kloxo has that option. I have no idea about it. But remember that I chosen 2 name servers for one domain before. Maybe it was my fault. But official Kloxo worked ok with this configuration.

**Comment by almas** [comment]
Update:
Slave server's named.master.conf file is empty. My fix also can't handle it. Now DNS zones only on master server. But can't created on Secondary name server. Please check and fix this bug.

Also two issue:
1. One small bug:
On a DNS Template Pool and also Servers page Up and Down buttons of list doesn't work.
Error on javascript console is:
ReferenceError: frm_client_b_dnssyncserver_list is not defined
2. When attempting to load a zone file this error can occur and cause bind start fails:

pop.company.net.zone:313: blah.pop.company.net: bad owner name (check-names)
zone pop.company.net/IN: loading from master file pop.company.net failed: bad owner name (check-names)
zone pop.company.net/IN: not loaded due to errors.

Solution:
To named.options.conf add options below:

```
    check-names master ignore;
    check-names slave ignore;
    check-names response ignore;
```
