### ISSUE TITLE
Kloxo reconigze wrong IP Address.

### ISSUE THREAD

**Issue by congdanh1608** [mustafaramadhan/kloxo#42]
Hello guys.
Here is my interface:
`eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1460
        inet 10.148.0.2  netmask 255.255.255.255  broadcast 10.148.0.2
        inet6 fe80::4001:aff:fe94:2  prefixlen 64  scopeid 0x20<link>
        ether 42:01:0a:94:00:02  txqueuelen 1000  (Ethernet)
        RX packets 15003  bytes 55507994 (52.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 13719  bytes 1056724 (1.0 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 6  bytes 300 (300.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6  bytes 300 (300.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
`
Because I use the VM instance of google cloud, so my VPS will have an external IP:  35.198.204.122  and internal IP: 10.148.0.2
After I install Kloxo success, the Kloxo doesn't receive my internal IP, how can I change it?

`
._/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/.
._/                                                                          _/.
._/ Congratulations. Kloxo-MR has been installed succesfully as 'MASTER'     _/.
._/                                                                          _/.
._/ You can connect to the server at:                                        _/.
._/     https://10.148.0.2:7777 - secure ssl connection, or                  _/.
._/     http://10.148.0.2:7778 - normal one.                                 _/.
._/                                                                          _/.
._/ The login and password are 'admin' and 'admin' for new install.          _/.
._/ After Logging in, you will have to change your password to               _/.
._/ something more secure.                                                   _/.
._/                                                                          _/.
._/ - Run 'sh /script/mysql-convert --engine=myisam' to minimize MySQLcccc   _/.
._/   memory usage. Or, go to 'admin->Webserver Configure'                   _/.
._/ - Run 'sh /script/make-slave' for change to 'SLAVE'                      _/.
._/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/.

`

I try to use "sh /script/fixdnschangeip", but it was not working.

Thanks.

**Comment by murshed** [comment]
Post your issue on the forum

**Comment by shahind** [comment]
i got this too

**Comment by congdanh1608** [comment]
@shahind : Hi guy!
I try to change port of console page and add more rule in firebase rules. That's working for me.

**Comment by mustafaramadhan** [comment]
Kloxo-MR still detect IP address from ifcfg-eth? files.
