### ISSUE TITLE
Error 404 - Not Found

### ISSUE THREAD

**Issue by fungo777** [mustafaramadhan/kloxo#6]
CentOS 6.6
Kloxo-MR 7.0.0.b-2015010905

Site Url : siltap.com

Time waits for the domain and nameserver the day
Why is this error?

I do not speak English well
Sorry

**Comment by mustafaramadhan** [comment]
Register as member to http://forum.mratwork.com.

No support here!.

**Comment by fungo777** [comment]
I'm sorry...

http://forum.mratwork.com.

member id : gesekgi

please
