### ISSUE TITLE
What are the suplementary features and functionalities we find with your kloxo forked software compare to the original one?

### ISSUE THREAD

**Issue by topstarnetwork** [mustafaramadhan/kloxo#8]
Hello,
What are the suplementary features and functionalities we find with your kloxo forked software compare to the original one?

regards, Heather

**Comment by topstarnetwork** [comment]
I also wanted to ask you what  are the differences with your hyawatha server and  hypervm softwares,
regards, Heather

**Comment by mustafaramadhan** [comment]
New features in Kloxo-MR 6.5/7.0 compare to Kloxo Official (6.1.19+):
1. Able to install to CentOS 6
2. Many options for webserver (apache, lighttpd, nginx and hiawatha) and their proxy (example nginx-proxy) - note: hiawatha and hiawatha-proxy no exist in Kloxo-MR 6.5
3. Many options for dnsserver (bind, lighttpd, pdns, nsd and yadifa) - pdns, nsd and yadifa no exist in Kloxo-MR 6.5
4. Better handle for spam for mailserver (qmail-toaster)
5. Better handle for security (prevent mysql-injection, implementing CSRF Token for post form, and many more)
6. New interface ('simplicity' skin) - note: only exist in Kloxo-MR 7.0
7. Can handle various php version (5.2-5.6; depend on CentOS version)
8. Can handle more php-types for apache (ruid2, itk, suphp, fcgid and php-fpm)
9. Possible using MySQL or MariaDB as database
10. Possible activate varnish/squid/ATF - note: only exist in Kloxo-MR 7.0
11. and etcetera

Note:
1. Hiawatha is web server like apache and nginx do
2. HyperVM is control panel (like Kloxo/Kloxo-MR) for VPS purpose where Kloxo/Kloxo-MR for webhosting purpose

**Comment by topstarnetwork** [comment]
Are you part of hiawatha, Hypervm and kloxo developer team or did you fork all this for your personal use?

Regards, Heather

**Comment by mustafaramadhan** [comment]
I am former dev of LxCenter.org (Kloxo and HyperVM producer). Introduce Kloxo-MR because no active devs in LxCenter (more than 1 year) and then the same time I found many issues related to security.

I am not hiawatha dev. Dev for hiawatha only Hugo Leisink (https://www.hiawatha-webserver.org) and the same as mine for Kloxo-MR (http://forum.mratwork.com). Kloxo-MR is the first and only webhosting control panel using hiawatha as web server option beside apache, lighttpd, nginx.

**Comment by topstarnetwork** [comment]
As you say that no active devs in LxCenter (more than 1 year) has worked neather upgraded Kloxo and HyperVM  do you think they still both can be used for production (are they stable) site compare to webmin:Virtualmin  and cloudmin?

**Comment by mustafaramadhan** [comment]
Better register to community.lxcenter.org (for Kloxo and HyperVM) and or forum.mratwork.com (for Kloxo-MR).

Please stop discussion here.
